"""PyTorch → C 数组导出脚本.

用法: python export/export_model.py

将以下资产导出为 C header (float 数组):
    - CNN 权重 + bias (m5_scene, K=8)
    - 子滤波器 Wc_v [C,S,Len]
    - 初级路径 Pri [E,R,Len]
    - 次级路径 Sec [E,S,Len]
    - 带通 FIR 系数
    - 场景定义 centroid 表 [K, S*C]

输出: data/ 目录下 .h 文件
"""
import os, sys, json, struct
import numpy as np
import scipy.io as sio
import torch
from pathlib import Path

# ── 配置 ──────────────────────────────────────
SCRIPT_DIR = Path(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = SCRIPT_DIR.parent
PYTHON_PROJ = Path(r'd:/VSCodeRepository/GFANC_Scene')
MODELS_DIR = PYTHON_PROJ / 'models'
PATHS_DIR = PYTHON_PROJ / 'Primary and Secondary Path'
OUT_DIR = PROJECT_DIR / 'data'
OUT_DIR.mkdir(exist_ok=True)

K = 8; S = 2; C = 15; E = 3; R = 1

# ── 工具函数 ──────────────────────────────────
def write_header(path, name, arr, comment=''):
    """Write a float array as C header."""
    arr = np.asarray(arr, dtype=np.float32).flatten()
    with open(path, 'w') as f:
        f.write(f'// Auto-generated by export_model.py\n')
        if comment:
            f.write(f'// {comment}\n')
        f.write(f'#ifndef {name}_H\n')
        f.write(f'#define {name}_H\n\n')
        f.write(f'#define {name}_LEN {len(arr)}\n')
        f.write(f'static const float {name}[{len(arr)}] = {{\n')
        for i in range(0, len(arr), 8):
            vals = ', '.join(f'{v:.9e}f' for v in arr[i:i+8])
            f.write(f'    {vals},\n')
        f.write('};\n\n')
        f.write(f'#endif // {name}_H\n')
    print(f'  {path.name}: {len(arr)} floats')

# ── 1. CNN 权重 ──────────────────────────────
print('Exporting CNN weights...')
sys.path.insert(0, str(PYTHON_PROJ))
from gfanc.Network import m5_scene

model = m5_scene(K=K, dropout=0.3)
pth = MODELS_DIR / 'MIMO_M5_Scene_Real.pth'
state = torch.load(str(pth), map_location='cpu', weights_only=True)
model.load_state_dict(state)
model.eval()

# 逐层提取
sd = model.state_dict()
layer_idx = 0

# conv_block: Conv1d(1,64,k=80,s=4,p=38) -> BN(64) -> no separate ReLU/MaxPool params
for key in ['conv_block.0.weight', 'conv_block.0.bias',  # Conv1d
            'conv_block.1.weight', 'conv_block.1.bias',    # BN gamma/beta
            'conv_block.1.running_mean', 'conv_block.1.running_var']:
    if key in sd:
        arr = sd[key].cpu().numpy()
        write_header(OUT_DIR / f'cnn_{layer_idx:02d}.h', f'CNN_{layer_idx:02d}', arr, f'{key} shape={list(arr.shape)}')
        layer_idx += 1
# BN eps and momentum
eps = 1e-5  # PyTorch default
momentum = 0.1

# res_blocks: 2 groups, each with 2 ResBlocks
# Each ResBlock: Conv1d(in,64,k=3,s=1,p=1) -> BN -> ReLU -> Conv1d(64,64,k=3,s=1,p=1) -> BN -> projection
for block_group in range(2):
    for block in range(2):
        prefix = f'res_blocks.{block_group}.{block}'
        for key_suffix in [
            'res.0.weight', 'res.0.bias',      # Conv1d #1
            'res.1.weight', 'res.1.bias',       # BN #1
            'res.1.running_mean', 'res.1.running_var',
            'res.3.weight', 'res.3.bias',       # Conv1d #2
            'res.4.weight', 'res.4.bias',       # BN #2
            'res.4.running_mean', 'res.4.running_var',
        ]:
            key = f'{prefix}.{key_suffix}'
            if key in sd:
                arr = sd[key].cpu().numpy()
                write_header(OUT_DIR / f'cnn_{layer_idx:02d}.h', f'CNN_{layer_idx:02d}', arr, f'{key} shape={list(arr.shape)}')
                layer_idx += 1
        # projection (1x1 conv if channel mismatch, first block only)
        proj_key = f'{prefix}.proj.weight'
        if proj_key in sd:
            arr = sd[proj_key].cpu().numpy()
            write_header(OUT_DIR / f'cnn_{layer_idx:02d}.h', f'CNN_{layer_idx:02d}', arr, f'{proj_key} shape={list(arr.shape)}')
            layer_idx += 1

# Linear: Linear(64, K)
for key in ['linear.weight', 'linear.bias']:
    if key in sd:
        arr = sd[key].cpu().numpy()
        write_header(OUT_DIR / f'cnn_{layer_idx:02d}.h', f'CNN_{layer_idx:02d}', arr, f'{key} shape={list(arr.shape)}')
        layer_idx += 1

# CNN architecture metadata
cnn_meta = {
    'n_layers': layer_idx,
    'K': K,
    'input_len': 16000,
    'conv0_in': 1, 'conv0_out': 64, 'conv0_kernel': 80, 'conv0_stride': 4, 'conv0_pad': 38,
    'pool0_kernel': 4, 'pool0_stride': 8,
    'res_groups': 2, 'res_per_group': 2,
    'res_kernel': 3, 'res_stride': 1, 'res_pad': 1, 'res_channels': 64,
    'pool_kernel': 4, 'pool_stride': 4,
    'fc_in': 64, 'fc_out': K,
    'bn_eps': 1e-5, 'bn_momentum': 0.1,
}

with open(OUT_DIR / 'cnn_meta.json', 'w') as f:
    json.dump(cnn_meta, f, indent=2)
print(f'  Total CNN layers: {layer_idx}')
print(f'  cnn_meta.json saved')

# 生成 CNN 权重索引文件
idx_lines = [
    '// Auto-generated CNN weight index',
    '#ifndef CNN_WEIGHTS_H',
    '#define CNN_WEIGHTS_H',
    '',
]
for i in range(layer_idx):
    name = f'CNN_{i:02d}'
    idx_lines.append(f'#include "cnn_{i:02d}.h"')
idx_lines.append('')
idx_lines.append(f'static const float *cnn_weights[{layer_idx}] = {{')
for i in range(layer_idx):
    idx_lines.append(f'    CNN_{i:02d},')
idx_lines.append('};')
idx_lines.append('')
idx_lines.append(f'#endif // CNN_WEIGHTS_H')

with open(OUT_DIR / 'cnn_weights.h', 'w') as f:
    f.write('\n'.join(idx_lines))
print(f'  cnn_weights.h generated ({layer_idx} weight arrays)')

# ── 2. 子滤波器 ──────────────────────────────
print('\nExporting sub-filters...')
mat = sio.loadmat(str(MODELS_DIR / 'MIMO_Pretrained_Control_filters_broadband.mat'))
Wc_v = mat['Wc_v']  # [C, S, Len]
write_header(OUT_DIR / 'sub_filters.h', 'SUB_FILTERS', Wc_v, f'Wc_v shape=({C},{S},{Wc_v.shape[2]})')

# ── 3. 声学路径 ──────────────────────────────
print('\nExporting acoustic paths...')
Pri = np.load(str(PATHS_DIR / 'primary_path_angle_0deg_left_3mic.npy'))  # [E, R, Len]
Sec = np.load(str(PATHS_DIR / 'secondary_path_measured.npy'))             # [E, S, Len]
write_header(OUT_DIR / 'pri_path.h', 'PRI_PATH', Pri, f'Primary path shape=({Pri.shape[0]},{Pri.shape[1]},{Pri.shape[2]})')
write_header(OUT_DIR / 'sec_path.h', 'SEC_PATH', Sec, f'Secondary path shape=({Sec.shape[0]},{Sec.shape[1]},{Sec.shape[2]})')

# ── 4. 场景定义 ──────────────────────────────
print('\nExporting scene definitions...')
with open(MODELS_DIR / 'scene_definitions_real.json') as f:
    scene_doc = json.load(f)
centroids = np.array([scene_doc['scenes'][str(k)]['centroid'] for k in range(K)], dtype=np.float32)
write_header(OUT_DIR / 'scene_defs.h', 'SCENE_DEFS', centroids, f'Centroid table [{K}, {S*C}]')

# ── 5. 带通 FIR ──────────────────────────────
print('\nExporting bandpass FIR...')
bp = sio.loadmat(str(MODELS_DIR / 'bandpass_filter_20_1500Hz.mat'))
bp_coeff = bp['fir_bandpass_coeff'].flatten()
write_header(OUT_DIR / 'bandpass_fir.h', 'BANDPASS_FIR', bp_coeff,
             f'Bandpass FIR 20-1500Hz, {len(bp_coeff)} taps')

# ── 6. 系统全局配置 ────────────────────────────
print('\nWriting system config...')
config_lines = [
    f'// System configuration — auto-generated',
    f'#ifndef GFANC_CONFIG_H',
    f'#define GFANC_CONFIG_H',
    f'',
    f'#define GFANC_FS         16000',
    f'#define GFANC_E          {E}',
    f'#define GFANC_S          {S}',
    f'#define GFANC_C          {C}',
    f'#define GFANC_K          {K}',
    f'#define GFANC_FILTER_LEN {Wc_v.shape[2]}',
    f'#define GFANC_PRI_LEN    {Pri.shape[2]}',
    f'#define GFANC_SEC_LEN    {Sec.shape[2]}',
    f'#define GFANC_INPUT_LEN  16000',
    f'#define GFANC_BP_LEN     {len(bp_coeff)}',
    f'#define GFANC_DSP_DELAY  16',
    f'#define GFANC_FADE_LEN   16',
    f'#define GFANC_SC_DIM     {(S * C)}  // S*C blend output dim',
    f'',
    f'#endif // GFANC_CONFIG_H',
]
with open(OUT_DIR / 'gfanc_config.h', 'w') as f:
    f.write('\n'.join(config_lines))

print(f'\nDone. All assets exported to {OUT_DIR}/')
print(f'Run: cd {PROJECT_DIR} && cmake -B build && cmake --build build')
