// Auto-generated by export_model.py
// linear.bias shape=[8]
#ifndef CNN_55_H
#define CNN_55_H

#define CNN_55_LEN 8
static const float CNN_55[8] = {
    9.552029520e-02f, 7.730639726e-02f, -1.457361877e-01f, 8.098693192e-02f, 6.029853225e-02f, -1.296493411e-01f, -8.556797355e-02f, 7.697340846e-02f,
};

#endif // CNN_55_H
